export const MAIN_COMMANDS = {
  CREATE_TASK: 'CREATE_TASK',
  KNOW_TG_ID: 'KNOW_TG_ID',
  SHOW_AG: 'SHOW_GOAL'
}

// CREATE TASK MENU
export const CT_MENU = {
  CT_COMMAND: `${MAIN_COMMANDS.CREATE_TASK}*CREATE_TASK`,
  INPUT_TASK_HEADER: `${MAIN_COMMANDS.CREATE_TASK}*INPUT_TASK_HEADER`,
  INPUT_TASK_DESC: `${MAIN_COMMANDS.CREATE_TASK}*INPUT_TASK_DESC`,
  CHOOSE_PRIORITY: `${MAIN_COMMANDS.CREATE_TASK}*CHOOSE_PRIORITY`,
  CHOSEN_PRIORITY: `${MAIN_COMMANDS.CREATE_TASK}*CHOSEN_PRIORITY`,
  CHOOSE_PERFORMER: `${MAIN_COMMANDS.CREATE_TASK}*CHOOSE_PERFORMER`,
  CHOSEN_PERFORMER: `${MAIN_COMMANDS.CREATE_TASK}*CHOSEN_PERFORMER`,
  CHOOSE_PROJECT: `${MAIN_COMMANDS.CREATE_TASK}*CHOOSE_PROJECT`,
  CHOSEN_PROJECT: `${MAIN_COMMANDS.CREATE_TASK}*CHOSEN_PROJECT`,
  FINISH_TASK: `${MAIN_COMMANDS.CREATE_TASK}*FINISH_TASK`,
  CANCEL_TASK: `${MAIN_COMMANDS.CREATE_TASK}*CANCEL_TASK`,
  BACK_CT_MENU: `${MAIN_COMMANDS.CREATE_TASK}*BACK_CT_MENU`
}

// SHOW ASSIGNED GOAL MENU
export const SAG_MENU = {
  SAG_COMMAND: `${MAIN_COMMANDS.SHOW_AG}*SHOW_ASSIGNED_GOAL`,
  CHOSEN_PROJECT: `${MAIN_COMMANDS.SHOW_AG}*CHOSEN_PROJECT`,
  CHOSEN_TASK: `${MAIN_COMMANDS.SHOW_AG}*CHOSEN_TASK`,
  BACK_MAIN_MENU: `${MAIN_COMMANDS.SHOW_AG}*BACK_MAIN_MENU`
}

// KNOW TG_ID MENU
export const KTGI_MENU = {
  KTGI_COMMAND: `${MAIN_COMMANDS.KNOW_TG_ID}*KNOW_TG_ID`,
  BACK_MAIN_MENU: `${MAIN_COMMANDS.KNOW_TG_ID}*BACK_MAIN_MENU`
}

export const PHRASES = {
  REFINE_HEADER: `💼 <b>CRM ALGO INC.</b>\n\nУточните заголовок:`,
  REFINE_DESC: `💼 <b>CRM ALGO INC.</b>\n\nУточните описание:`,
  REFINE_PRIORITY: `💼 <b>CRM ALGO INC.</b>\n\nУкажите приоритет:`,
  REFINE_PROJECT: `💼 <b>CRM ALGO INC.</b>\n\nВыбери проект:`,
  REFINE_PERFORMER: `💼 <b>CRM ALGO INC.</b>\n\nВыбери исполнителя:`,
  INCORRECT_INPUT: `💼 <b>CRM ALGO INC.</b>\n\nОдно из полей не заполнено, проверь`
}